services:

###> doctrine/doctrine-bundle ###
  database:
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    container_name: emonado_mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always

    ports:
      - "3307:3306"   # ✅ IMPORTANT (expose MySQL vers ton PC)

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: emonado
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      TZ: UTC

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-proot"]
      timeout: 5s
      retries: 5
      start_period: 60s

    volumes:
      - database_data:/var/lib/mysql:rw
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d:ro
###< doctrine/doctrine-bundle ###


###> symfony/mailer ###
  mailer:
    image: axllent/mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
###< symfony/mailer ###


###> symfony/mercure-bundle ###
  mercure:
    image: dunglas/mercure
    container_name: emonado_mercure
    restart: unless-stopped

    environment:
<<<<<<< HEAD
      MERCURE_PUBLISHER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
      MERCURE_SUBSCRIBER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
=======
      # Uncomment the following line to disable HTTPS,
      #SERVER_NAME: ':80'
      MERCURE_PUBLISHER_JWT_KEY: 'maSuperCleSecrete123!'
      MERCURE_SUBSCRIBER_JWT_KEY: 'maSuperCleSecrete123!'
      # Set the URL of your Symfony project (without trailing slash!) as value of the cors_origins directive
>>>>>>> 020c78a (finalVersionByRimm)
      MERCURE_EXTRA_DIRECTIVES: |
        cors_origins http://127.0.0.1:8000

    command: /usr/bin/caddy run --config /etc/caddy/dev.Caddyfile

    ports:
      - "3000:80"   # ✅ accès au hub mercure si besoin

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/healthz"]
      timeout: 5s
      retries: 5
      start_period: 60s

    volumes:
      - mercure_data:/data
      - mercure_config:/config
###< symfony/mercure-bundle ###


volumes:
  database_data:
  mercure_data:
  mercure_config: